export const COUNTRIES = [
  { code: 'US', name: 'United States', languages: ['English', 'Spanish'] },
  { code: 'GB', name: 'United Kingdom', languages: ['English'] },
  { code: 'CA', name: 'Canada', languages: ['English', 'French'] },
  { code: 'AU', name: 'Australia', languages: ['English'] },
  { code: 'PH', name: 'Philippines', languages: ['English', 'Tagalog', 'Filipino'] },
  { code: 'IN', name: 'India', languages: ['Hindi', 'English', 'Bengali', 'Telugu', 'Marathi', 'Tamil', 'Urdu'] },
  { code: 'DE', name: 'Germany', languages: ['German'] },
  { code: 'FR', name: 'France', languages: ['French'] },
  { code: 'IT', name: 'Italy', languages: ['Italian'] },
  { code: 'ES', name: 'Spain', languages: ['Spanish', 'Catalan', 'Galician', 'Basque'] },
  { code: 'MX', name: 'Mexico', languages: ['Spanish'] },
  { code: 'BR', name: 'Brazil', languages: ['Portuguese'] },
  { code: 'JP', name: 'Japan', languages: ['Japanese'] },
  { code: 'KR', name: 'South Korea', languages: ['Korean'] },
  { code: 'CN', name: 'China', languages: ['Chinese (Mandarin)', 'Cantonese'] },
  { code: 'ZA', name: 'South Africa', languages: ['English', 'Afrikaans', 'Zulu', 'Xhosa'] },
  { code: 'NG', name: 'Nigeria', languages: ['English', 'Hausa', 'Yoruba', 'Igbo'] },
  { code: 'EG', name: 'Egypt', languages: ['Arabic'] },
  { code: 'SA', name: 'Saudi Arabia', languages: ['Arabic'] },
  { code: 'AE', name: 'United Arab Emirates', languages: ['Arabic', 'English'] },
  { code: 'RU', name: 'Russia', languages: ['Russian'] },
  { code: 'TR', name: 'Turkey', languages: ['Turkish'] },
  { code: 'ID', name: 'Indonesia', languages: ['Indonesian', 'Javanese'] },
  { code: 'MY', name: 'Malaysia', languages: ['Malay', 'English', 'Chinese', 'Tamil'] },
  { code: 'SG', name: 'Singapore', languages: ['English', 'Malay', 'Mandarin', 'Tamil'] },
  { code: 'NZ', name: 'New Zealand', languages: ['English', 'Māori'] },
  { code: 'IE', name: 'Ireland', languages: ['English', 'Irish'] },
  { code: 'NL', name: 'Netherlands', languages: ['Dutch', 'English'] },
  { code: 'SE', name: 'Sweden', languages: ['Swedish', 'English'] },
  { code: 'NO', name: 'Norway', languages: ['Norwegian', 'English'] },
  { code: 'DK', name: 'Denmark', languages: ['Danish', 'English'] },
  { code: 'FI', name: 'Finland', languages: ['Finnish', 'Swedish', 'English'] },
  { code: 'PL', name: 'Poland', languages: ['Polish'] },
  { code: 'UA', name: 'Ukraine', languages: ['Ukrainian', 'Russian'] },
  { code: 'AR', name: 'Argentina', languages: ['Spanish'] },
  { code: 'CO', name: 'Colombia', languages: ['Spanish'] },
  { code: 'CL', name: 'Chile', languages: ['Spanish'] },
  { code: 'PE', name: 'Peru', languages: ['Spanish'] },
  { code: 'VE', name: 'Venezuela', languages: ['Spanish'] },
  { code: 'TH', name: 'Thailand', languages: ['Thai'] },
  { code: 'VN', name: 'Vietnam', languages: ['Vietnamese'] },
  { code: 'PK', name: 'Pakistan', languages: ['Urdu', 'English', 'Punjabi'] },
  { code: 'BD', name: 'Bangladesh', languages: ['Bengali', 'English'] },
  { code: 'IL', name: 'Israel', languages: ['Hebrew', 'Arabic', 'English'] },
  { code: 'CH', name: 'Switzerland', languages: ['German', 'French', 'Italian', 'Romansh'] },
  { code: 'AT', name: 'Austria', languages: ['German'] },
  { code: 'BE', name: 'Belgium', languages: ['Dutch', 'French', 'German'] },
  { code: 'PT', name: 'Portugal', languages: ['Portuguese'] },
  { code: 'GR', name: 'Greece', languages: ['Greek'] },
  { code: 'CZ', name: 'Czech Republic', languages: ['Czech'] },
  { code: 'HU', name: 'Hungary', languages: ['Hungarian'] },
  { code: 'RO', name: 'Romania', languages: ['Romanian'] },
];
